- name: Install php repo
  shell: "https_proxy={{ proxy_env.http_proxy }} add-apt-repository -y ppa:ondrej/php"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependecies
  apt:
    pkg:
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}"
      - "nginx"
    state: latest
