- name: Setup proxy server for apt
  lineinfile:
    path: /etc/etc/apt.conf
    regexp: ^Acquire::http::Proxy
    line: Acquire::http::Proxy "{{ proxy_env.http_proxy }}";
    create: yes
  when: proxy_env is defined

- name: Update cache
  apt:
    update_cache: yes
