- name: Install the remi repo
  command: dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm

- name: Enable remi php repo
  command: dnf module enable -y php:remi-{{ php_version }}


- name: Install dependecies
  dnf:
    name:
      - php-mysql
      - php-fpm
      - php-gd 
      - php
      - nginx
    state: latest
